# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy manifests
COPY package.json pnpm-lock.yaml tsconfig.json ./

# Copy source
COPY src ./src
COPY templates ./templates

# Install deps and build
RUN npm install --ignore-scripts && npm run build

# Runtime stage
FROM node:lts-alpine AS runtime
WORKDIR /app

# Copy build artifacts and dependencies
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY package.json ./

ENTRYPOINT ["node", "dist/index.js"]
